platform:ios,’8.0’
#use_frameworks!
#inhibit_all_warnings! #消除第三方仓库的警告
source 'git@github.com:CocoaPods/Specs.git'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = "NO"
        end
    end
end

#install! 'cocoapods', generate_multiple_pod_projects: true

target :'DoraemonKitDemo' do
  pod 'DoraemonKit', :subspecs => ['Core','WithLogger','WithDatabase'], :path => '../../'
  #pod 'fishhook', :git => 'git@github.com:facebook/fishhook.git', :configurations => ['Debug']
  pod 'YYDebugDatabase', :git => 'https://github.com/y500/YYDebugDatabase.git', :configurations => ['Debug']
end
